# Used for test only
version: "3.3"
services:

  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    ports:
      - "7080:80"
      - "7088:8888"
    volumes:
      - $PWD:/app
    env_file:
      - .env
    environment:
#      - SERVER_NAME=${DOMAIN?Variable not set}
#      - SERVER_HOST=https://${DOMAIN?Variable not set}
      # use environment variable to override mongodb settings for test
      - db__host=mongo
      - db__port=${DB_PORT}
      - db__username=${DB_USERNAME}
      - db__password=${DB_PASSWORD}
      - db__database=${DB_DATABASE}
      # Backend
      - FIRST_SUPERUSER=admin@localhost.com
      - FIRST_SUPERUSER_PASSWORD=admin
      # development
      - LOG_LEVEL=debug
      - JUPYTER=jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.custom_display_url=http://127.0.0.1:8888 --log-level=0
    build:
      context: ./
      dockerfile: Dockerfile
      args:
#        INSTALL_JUPYTER: ${INSTALL_JUPYTER-true}
#        INSTALL_DEV: ${INSTALL_DEV-true}
        INSTALL_TEST: ${INSTALL_TEST-true}
    stdin_open: true
    tty: true
    depends_on:
      - mongo
    command: /start-reload.sh

  mongo:
    image: mongo:4.2.22
    ports:
      - "7017:${DB_PORT?Variable not set}"
    env_file:
      - .env
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passwd123
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
    volumes:
      - "$PWD/scripts/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
